### ISSUE TITLE
Consider making multiple stylesheets

### ISSUE THREAD

**Issue by KhalilKhunji** [Shahstaa/Agenda-Hub-Project#3]
https://github.com/Shahstaa/Agenda-Hub-Project/blob/28c4cab1568ffbc239571fb713bd43ff2aa4f0fe/public/stylesheets/style.css#L1
This file is quite long at 900 lines; CSS would be difficult to manage if you have it all in one place. May be easier to divide each page's CSS into its own CSS file, e.g. index.css, show.css, edit.css, etc. 

Of course, you can keep style.css to be your base styling to keep a consistent theme throughout the website for any CSS you're reusing on multiple pages.

**Comment by Shahstaa** [comment]
I had considered splitting the CSS into separate files for each page, like index.css, show.css, and edit.css. However, I was worried that this might lead to complications when linking them or maintaining consistency across styles.

**Comment by KhalilKhunji** [comment]
Sure! If you already have an idea of the scope of your project, you can plan ahead and start with multiple stylesheets to begin with.
